# fly.toml app configuration file generated for bot-beard on 2023-12-06T06:05:03+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bot-beard"
primary_region = "sin"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
